jira:
  url: https://jira.url/jira

holiday:
  url: https://api.calendario.com.br/?json=true
  token: seuToken

spring:
  application:
    name: jirareport
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jirareport
    username: ${USER}
    password: ${PASSWORD:123123}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names:
    - findAllHolidaysInCity
    - findAllFields
    - retrieveCurrentUserConfig
    caffeine:
      spec: expireAfterWrite=15m

  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
