jira:
  url: ${JIRA_URL:-https://jira.url/jira}

holiday:
  url: https://api.calendario.com.br
  token: ${CALENDARIO_TOKEN:-seuCalendarioToken}

security:
  key: ${SECRET_KEY:-pleasechangemeforthegodsake}

spring:
  application:
    name: jirareport
  datasource:
    url: jdbc:${DATABASE_URL:-postgresql://database:5432/jirareport}
    username: ${DATABASE_USER:-root}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names:
      - findAllHolidaysInCity
      - findAllFields
    caffeine:
      spec: expireAfterWrite=15m
  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
  sleuth:
    sampler:
      probability: 1.0

feign:
  client:
    config:
      default:
        logger-level: FULL
