jira:
    url: https://jira.url/jira

holiday:
  url: https://api.calendario.com.br/?json=true
  token: seuToken

spring:
  application:
    name: jirareport
  datasource:
    url: jdbc:postgresql://localhost:5432/jirareport
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
