jira:
  url: https://jira.url/jira

holiday:
  url: https://api.calendario.com.br
  token: seuToken

security:
  key: super-secret-key

spring:
  application:
    name: jirareport
  datasource:
    url: jdbc:postgresql://localhost:5432/jirareport
    username: ${USER}
    password: ${PASSWORD:123123}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names:
    - findAllHolidaysInCity
    - findAllFields
    caffeine:
      spec: expireAfterWrite=15m
  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
  sleuth:
    sampler:
      probability: 1.0
