jira:
  url: https://jira.url/jira

holiday:
  url: https://api.calendario.com.br
  token: seuToken

security:
  key: super-secret-key

spring:
  application:
    name: jirareport
  datasource:
    url: jdbc:postgresql://localhost:5432/jirareport
    username: ${USER}
    password: ${PASSWORD:123123}
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names:
    - findAllHolidaysInCity
    - findAllFields
    - retrieveCurrentUserConfig
    caffeine:
      spec: expireAfterWrite=15m
  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
